### ISSUE TITLE
Gradle plugin does not correctly pull or update GatorGrader

### ISSUE THREAD

**Issue by schultzh** [GatorEducator/gatorgradle#29]
When attempting to use gradle grade on assignments, I continually get an error saying `gator grader does not exist.` However, the program is installed on my laptop. I feel that this means the program will not pull gradle grade to run it in terminal.

**Comment by gkapfham** [comment]
Hello @schultzh and @Michionlion, I have transferred this issue to this repository since it is most likely an issue with the Gradle plugin and not the GatorGrader program itself. Do you both agree?

**Comment by Michionlion** [comment]
I agree. It would be helpful to have the full log, @schultzh, as well. This is likely a human error at some point -- perhaps a typo somewhere.

**Comment by gkapfham** [comment]
Hi @schultzh, I should clarify @Michionlion's comment: even if this is some issue with the way in which something is configured on your laptop (which it may or may not be), it would be great to learn more details from you. This is particularly important because other people who use the GatorGrader tool and its Gradle plugin may also do the same thing that you have done and once we know the issue we should document it in the README file. So, please investigate further and report back when you have time. Thanks @schultzh for reporting this issue, we really appreciate it!

**Comment by schultzh** [comment]
@gkapfham 
yes this occurs with all of my assignments now, but it did not occur up until lab 7 

version for gatorgrader in my ```.local/share/virtualenvs file gatorgrader-7UYporlp```

MacBook Air macOS 10.14

**Comment by schultzh** [comment]
@gkapfham 
could you please advise me on how to delete the directory?

**Comment by Michionlion** [comment]
You can run this command: `rm -rf ~/.local/share/gatorgrader`

**Comment by gkapfham** [comment]
So, @schultzh, please let us know what happens once you delete the `gatorgrader` directory and then try the process again. Thanks for investigating this further!

**Comment by schultzh** [comment]
I deleted the directory and reinstalled gatorgrader in the .local file. The same error still occurs: ```gatorgrader not installed```

**Comment by Michionlion** [comment]
Hi @schultzh, can you please delete the `~/.local/share/gatorgrader` folder again, and run `gradle grade` on a project, and then post the output visible in the terminal?

Also, just to confirm, you are running this on a Linux computer right?

**Comment by schultzh** [comment]
```Installing GatorGrader...
Cloning into '/Users/hannahschultz/.local/share/gatorgrader'...
Installing GatorGrader python dependencies...
Installing dependencies from Pipfile.lock (53e488)...
Traceback (most recent call last):
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
Finished GatorGrader install!
ERROR: GatorGrader management failed, could not install dependencies!
Command run: 'pipenv' 'install'
OUTPUT: Installing dependencies from Pipfile.lock (53e488)...
Traceback (most recent call last):
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
Deleting /Users/hannahschultz/.local/share/gatorgrader

> Task :grade FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grade'.
> GatorGrader not installed!
```

**Comment by schultzh** [comment]
@Michionlion No, this is on my Macbook which does not use Linux software.

**Comment by Michionlion** [comment]
Hmm. Looks like this is actually a problem with python or pipenv. Specifically a module called `module`. Likely it can be resolved with an update and reinstall of python and pipenv. Can you run `pyenv install 3.7.2` and then `pyenv global 3.7.2`. You'll also need to make sure you installed pipenv with Homebrew.

Before you try running `gradle grade` make sure you restart your terminal window.

Note that you don't need to delete the directory - this was a failed installation so GatorGradle automatically deletes it.

**Comment by Michionlion** [comment]
@schultzh Did reinstalling fix the problem? If not, could you post the results from `gradle grade` again now, after reinstalling?

**Comment by schultzh** [comment]
@Michionlion Where does pipenv need to be installed? .local?

**Comment by Michionlion** [comment]
There is no location required -- you take a look at the documentation in the [pipenv repository](https://github.com/pypa/pipenv), but if you have [homebrew](https://brew.sh/) installed, you can just run `brew install pipenv`. You'll need to run `brew update` first. If you are still having troubles with this, feel free to come into my office hours this Friday (starting at 12:30) and we can work on it together.

**Comment by schultzh** [comment]
Okay! I'll work on it further tonight and keep you updated. Thank you!

**Comment by schultzh** [comment]
after having to download xcode command line tools, this is the error I'm running into:

```
==> Summary
🍺  /usr/local/Cellar/sqlite/3.26.0_1: 11 files, 3.7MB
==> Installing pipenv dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.mojave.bottle.tar.
######################################################################## 100.0%
==> Pouring xz-5.2.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
==> Installing pipenv dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.2_1.mojave.bottl
######################################################################## 100.0%
==> Pouring python-3.7.2_1.mojave.bottle.1.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
```

**Comment by Michionlion** [comment]
You should run the installation with `sudo` -- i.e. `sudo brew install pipenv`. This gives `homebrew` administrator privileges.

**Comment by schultzh** [comment]
```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by Michionlion** [comment]
hmm, it may be the case then that there is no actual problem.

To make sure, first run `brew uninstall --force pipenv`. Then exit the terminal, and start a new one. Then, run `brew update` followed by `brew install pipenv`. If that still reports errors ("Permission denied", etc.), post that. If not, try `gradle grade` again.

**Comment by schultzh** [comment]
after running those commands and trying ```gradle grade``` again I am still recieving this error: 
```
Installing GatorGrader...
Cloning into '/Users/hannahschultz/.local/share/gatorgrader'...
Installing GatorGrader python dependencies...
Installing dependencies from Pipfile.lock (53e488)...
Traceback (most recent call last):
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
Finished GatorGrader install!
ERROR: GatorGrader management failed, could not install dependencies!
Command run: 'pipenv' 'install'
OUTPUT: Installing dependencies from Pipfile.lock (53e488)...
Traceback (most recent call last):
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/Users/hannahschultz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
Deleting /Users/hannahschultz/.local/share/gatorgrader

> Task :grade FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grade'.
> GatorGrader not installed!
```

**Comment by Michionlion** [comment]
I'm not sure what's going on but it looks like you didn't change the python version - it's still trying to look for things in 3.6.3. I think the easiest thing at this point is to come in to a lab session or my office hours. I'm not sure what the problem is but we can figure it out faster together.

**Comment by schultzh** [comment]
Okay. I am not available during your office hours, but let me know what lab sessions work for you.
My CS labs are Mondays 2:30 - 4:30.

**Comment by Michionlion** [comment]
@schultzh We can meet before (preferably) or after your next lab, Monday the 21st, if that works for you.

**Comment by schultzh** [comment]
@Michionlion I will not have lab on Monday due to it being MLK day.

**Comment by Michionlion** [comment]
Okay, I forgot about that. Why don't you email me the times you're in Alden, and we can find a time that works? (mahlauheinerts@allegheny.edu)

**Comment by gkapfham** [comment]
Hi @schultzh and @Michionlion, is it possible for you both to schedule a meeting with me during my office hours? We could work together for 15-30 minutes sometime in the following week and then try to better understand the problem and see if we need to develop a solution. We can then continue the conversation here, as appropriate. Thanks for continuing to work on this issue!

**Comment by Michionlion** [comment]
@gkapfham, Hannah and I actually solved the issue already. It was related to the fact that `zlib` does not install properly through `homebrew` on macOS Mojave, thus making the python build executed by `pyenv` fail, and cascading the errors throughout the entire process. The solution is to install zlib using some macOS specific commands, as detailed in [issue #1219](https://github.com/pyenv/pyenv/issues/1219) in the `pyenv` repository. As this has been solved, I will close this issue. If in the future it appears a different problem was the culprit, please feel free to reopen this issue!
