### ISSUE TITLE
missing common mark module

### ISSUE THREAD

**Issue by schultzh** [GatorEducator/gatorgradle#47]
I cannot currently use `gradle grade` effectively on my personal laptop. I am receiving the following errors: 

```
"Traceback (most recent call last):
  File "/Users/hannahschultz/.local/share/gatorgrader/gatorgrader.py", line 5, in <module>
    from gator import orchestrate
  File "/Users/hannahschultz/.local/share/gatorgrader/gator/orchestrate.py", line 11, in <module>
    from gator import invoke  # noqa: F401
  File "/Users/hannahschultz/.local/share/gatorgrader/gator/invoke.py", line 6, in <module>
    from gator import fragments
  File "/Users/hannahschultz/.local/share/gatorgrader/gator/fragments.py", line 6, in <module>
    import commonmark
ModuleNotFoundError: No module named 'commonmark'"
```

This error repeats for each check within the repository. I assume that it is something my laptop is missing, however, I wanted to bring it up and make sure.

**Comment by gkapfham** [comment]
I think that this issue has been resolved, @schultzh and @Michionlion. Are you okay with closing it now? The only take home point is that we need to ensure that people use new versions of our plugin, which, going forward, I anticipate will not be a major concern. Thanks!
